# Generated by Django 4.1 on 2022-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My New Blog Site!', max_length=255),
        ),
    ]
